name: Generate Stats Images

on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
  
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          architecture: 'x64'
  
      - name: Install requirements
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
  
      - name: Generate images
        run: python generate_images.py
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDED: ${{ secrets.EXCLUDED }}
          EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
          EXCLUDE_FORKED_REPOS: false
  
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update generated files

